import { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    date: "Summer 2025",
    title: "AIVA - AI Vocal Assistant",
    description:
      "AIVA is an AI-powered vocal assistant that helps users manage their tasks and schedule through voice commands.",
    href: "https://aiva.eliotatlani.fr",
    technologies: [
      "ReactJS",
      "TypeScript",
      "TailwindCSS",
      "FastAPI",
      "Google ADK",
      "NeonDB",
    ],
    github: "https://github.com/EliotAtlani/portefolio-links",
    colorCard: "text-[#8F1538]",
    colors: [
      [143, 21, 56],
      [217, 89, 126],
    ],
    borderColor: "border-[#8F1538]",
  },
  {
    date: "April 2025",
    title: "AI-generated image detector",
    description:
      "AI-powered detector that identifies whether an image was generated by artificial intelligence or is authentic, using advanced machine learning models for accurate classification.",
    href: null,
    technologies: ["Python", "TensorFlow", "Scikit Learn", "OpenCV", "FastAPI"],
    github: "https://github.com/EliotAtlani/ai-image-detector",
    colorCard: "text-[#10B981]",
    colors: [
      [16, 185, 129],
      [52, 211, 153],
    ],
    borderColor: "border-[#10B981]",
  },
  {
    date: "April 2025",
    title: "Travel Salesman Optimization",
    description:
      "Advanced optimization algorithms for solving the Traveling Salesman Problem using genetic algorithms, simulated annealing, and machine learning approaches with interactive visualization.",
    href: "https://eliotatlani.fr/pdf/cs_2050.pdf",
    technologies: ["C++", "OpenMP", "MPI"],
    github: null,
    colorCard: "text-[#F59E0B]",
    colors: [
      [245, 158, 11],
      [251, 191, 36],
    ],
    borderColor: "border-[#F59E0B]",
  },
  {
    date: "December 2024",
    title: "Spotify Hit Predicts",
    description:
      "Machine learning model that predicts whether a song will become a hit on Spotify by analyzing audio features, artist popularity, and market trends with high accuracy.",
    href: null,
    technologies: [
      "Python",
      "Scikit-learn",
      "Pandas",
      "Matplotlib",
      "XGBoost",
      "Jupyter",
      "Seaborn",
    ],
    github: "https://github.com/EliotAtlani/hit-predict",
    colorCard: "text-[#1DB954]",
    colors: [
      [29, 185, 84],
      [30, 215, 96],
    ],
    borderColor: "border-[#1DB954]",
  },
  {
    date: "December 2024",
    title: "Bartender LLM",
    description:
      "AI-powered bartender assistant that recommends cocktails based on available ingredients, preferences, and dietary restrictions using natural language processing.",
    href: null,
    technologies: [
      "Python",
      "LangChain",
      "FastAPI",
      "ReactJS",
      "TypeScript",
      "ChromaDB",
      "Docker",
      "Ansible",
      "Kubernetes",
      "GCP",
    ],
    github: null,
    colorCard: "text-[#8B5CF6]",
    colors: [
      [139, 92, 246],
      [167, 139, 250],
    ],
    borderColor: "border-[#8B5CF6]",
  },
  {
    date: "July 2024",
    title: "Connectly",
    description:
      "Connectly is live chat web application inspired by WhatsApp. Users can create groups, send messages, and share files to their friends in real-time",
    href: "https://connectly.eliotatlani.fr",
    technologies: [
      "ReactJS",
      "TypeScript",
      "TailwindCSS",
      "Socket.IO",
      "ExpressJS",
      "Docker",
      "PostgreSQL",
    ],
    github: "https://github.com/EliotAtlani/portefolio-links",
    colorCard: "text-[#8F1538]",
    colors: [
      [143, 21, 56],
      [217, 89, 126],
    ],
    borderColor: "border-[#8F1538]",
  },
  {
    date: "June 2024",
    title: "FaceAuth",
    description:
      "FaceAuth is a facial recognition system that allows you to connect to your accounts without having to enter a password.",
    href: "https://faceauth.eliotatlani.fr",
    technologies: [
      "ReactJS",
      "TypeScript",
      "TailwindCSS",
      "ViteJS",
      "FastAPI",
      "Pinecone",
      "Docker",
    ],
    github: "https://github.com/EliotAtlani/portefolio-links",
    colorCard: "text-[#3B82F6]",
    colors: [
      [59, 130, 246],
      [139, 92, 246],
    ],
    borderColor: "border-[#3B82F6]",
  },
  {
    date: "July 2024",
    title: "FileSwap",
    description:
      "FileSwap is a versatile file converter that allows you to easily convert, compress, and resize your files across various formats.",
    href: "https://fileswap.eliotatlani.fr",
    technologies: [
      "ReactJS",
      "TypeScript",
      "ViteJS",
      "NestJS",
      "GitHub Actions",
      "Docker",
    ],
    github: "https://github.com/EliotAtlani/portefolio-links",
    colorCard: "text-[#77FCDF]",
    colors: [
      [16, 224, 92],
      [119, 252, 223],
      [7, 115, 27],
    ],
    borderColor: "border-[#77FCDF]",
  },

  {
    date: "May 2023",
    title: "Toss Application",
    description:
      "The TOSS is a 4500-student sport tournament. The application allows you to follow the score of the matches, the ranking of the teams, and the schedule of the matches.",
    href: "https://apps.apple.com/fr/app/toss-2024/id6446198811",
    technologies: ["React Native", "ExpressJS", "MySQL", "Expo", "AWS EC2"],
    github: null,
    colorCard: "text-[#ffaa00]",
    colors: [
      [255, 170, 0],
      [245, 245, 10],
      [184, 115, 18],
    ],
    borderColor: "border-[#ffaa00]",
  },
];
